function [dimensions, images] = load_images()
    images_dir = 'images/';
    image_names = {
        'zero.jpg', ...
        'one.jpg', ...
        'two.jpg', ...
        'three.jpg', ...
        'four.jpg', ...
        'five.jpg', ...
        'six.jpg', ...
        'seven.jpg', ...
        'eight.jpg', ...
        'nine.jpg'
    };
    color_image_names = {
        'zero_color.jpg', ...
        'one_color.jpg', ...
        'two_color.jpg', ...
        'three_color.jpg', ...
        'four_color.jpg', ...
        'five_color.jpg', ...
        'six_color.jpg', ...
        'seven_color.jpg', ...
        'eight_color.jpg', ...
        'nine_color.jpg'
    };
    gray_image_names = {
        'zero_gray.jpg', ...
        'one_gray.jpg', ...
        'two_gray.jpg', ...
        'three_gray.jpg', ...
        'four_gray.jpg', ...
        'five_gray.jpg', ...
        'six_gray.jpg', ...
        'seven_gray.jpg', ...
        'eight_gray.jpg', ...
        'nine_gray.jpg'
    };
    bin_color_image_names = {
        'zero_binare_color.jpg', ...
        'one_binare_color.jpg', ...
        'two_binare_color.jpg', ...
        'three_binare_color.jpg', ...
        'four_binare_color.jpg', ...
        'five_binare_color.jpg', ...
        'six_binare_color.jpg', ...
        'seven_binare_color.jpg', ...
        'eight_binare_color.jpg', ...
        'nine_binare_color.jpg'
    };
    images = {};
    for name = image_names;
        image = imread(fullfile(images_dir, name{1}));        
        % image = rgb2gray(image);
        images{end + 1} = image;
    end
    dimensions = size(image);
    disp(dimensions)
end
