function [dimensions, images] = load_images()
    images_dir = 'images\';
    image_names = {
        'zero.jpg', ...
        'one.jpg', ...
        'two.jpg', ...
        'three.jpg', ...
        'four.jpg', ...
        'five.jpg', ...
        'six.jpg', ...
        'seven.jpg', ...
        'eight.jpg', ...
        'nine.jpg',...
        'a.jpg',...
        'b.jpg',...
        'c.jpg',...
        'd.jpg',...
        'e.jpg',...
        'f.jpg',...
        'g.jpg',...
        'h.jpg',...
        'i.jpg',...
        'j.jpg',...
        'k.jpg',...
        'l.jpg',...
        'm.jpg',...
        'n.jpg',...
        'o.jpg',...
        'p.jpg',...
        'q.jpg',...
        'r.jpg',...
        's.jpg',...
        't.jpg',...
        'u.jpg',...
        'w.jpg',...
        'v.jpg',...
        'x.jpg',...
        'y.jpg',...
        'z.jpg'
    };
    emergent_bg_image_names = {
        'emergent_colour_zero_bg.jpg', ...
        'emergent_colour_one_bg.jpg', ...
        'emergent_colour_two_bg.jpg', ...
        'emergent_colour_three_bg.jpg', ...
        'emergent_colour_four_bg.jpg', ...
        'emergent_colour_five_bg.jpg', ...
        'emergent_colour_six_bg.jpg', ...
        'emergent_colour_seven_bg.jpg', ...
        'emergent_colour_eight_bg.jpg', ...
        'emergent_colour_nine_bg.jpg',...
        'emergent_colour_a_bg.jpg',... % 10
        'emergent_colour_b_bg.jpg',...
        'emergent_colour_c_bg.jpg',...
        'emergent_colour_d_bg.jpg',...
        'emergent_colour_e_bg.jpg',...
        'emergent_colour_f_bg.jpg',... %15
        'emergent_colour_g_bg.jpg',...
        'emergent_colour_h_bg.jpg',...
        'emergent_colour_i_bg.jpg',...
        'emergent_colour_j_bg.jpg',...
        'emergent_colour_k_bg.jpg',... %20
        'emergent_colour_l_bg.jpg',...
        'emergent_colour_m_bg.jpg',...
        'emergent_colour_n_bg.jpg',...
        'emergent_colour_o_bg.jpg',...
        'emergent_colour_p_bg.jpg',... %25
        'emergent_colour_q_bg.jpg',...
        'emergent_colour_r_bg.jpg',...
        'emergent_colour_s_bg.jpg',...
        'emergent_colour_t_bg.jpg',...
        'emergent_colour_u_bg.jpg',... %30
        'emergent_colour_w_bg.jpg',...
        'emergent_colour_v_bg.jpg',...
        'emergent_colour_x_bg.jpg',...
        'emergent_colour_y_bg.jpg',...
        'emergent_colour_z_bg.jpg'
    };
    bg_image_names = {
        'zero_bg.jpg', ...
        'one_bg.jpg', ...
        'two_bg.jpg', ...
        'three_bg.jpg', ...
        'four_bg.jpg', ...
        'five_bg.jpg', ...
        'six_bg.jpg', ...
        'seven_bg.jpg', ...
        'eight_bg.jpg', ...
        'nine_bg.jpg',...
        'a_bg.jpg',...
        'b_bg.jpg',...
        'c_bg.jpg',...
        'd_bg.jpg',...
        'e_bg.jpg',...
        'f_bg.jpg',...
        'g_bg.jpg',...
        'h_bg.jpg',...
        'i_bg.jpg',...
        'j_bg.jpg',...
        'k_bg.jpg',...
        'l_bg.jpg',...
        'm_bg.jpg',...
        'n_bg.jpg',...
        'o_bg.jpg',...
        'p_bg.jpg',...
        'q_bg.jpg',...
        'r_bg.jpg',...
        's_bg.jpg',...
        't_bg.jpg',...
        'u_bg.jpg',...
        'w_bg.jpg',...
        'v_bg.jpg',...
        'x_bg.jpg',...
        'y_bg.jpg',...
        'z_bg.jpg'
    };
    emergent_image_names = {
        'emergent_colour_zero.jpg', ...
        'emergent_colour_one.jpg', ...
        'emergent_colour_two.jpg', ...
        'emergent_colour_three.jpg', ...
        'emergent_colour_four.jpg', ...
        'emergent_colour_five.jpg', ...
        'emergent_colour_six.jpg', ...
        'emergent_colour_seven.jpg', ...
        'emergent_colour_eight.jpg', ...
        'emergent_colour_nine.jpg',...
        'emergent_colour_a.jpg',...
        'emergent_colour_b.jpg',...
        'emergent_colour_c.jpg',...
        'emergent_colour_d.jpg',...
        'emergent_colour_e.jpg',...
        'emergent_colour_f.jpg',...
        'emergent_colour_g.jpg',...
        'emergent_colour_h.jpg',...
        'emergent_colour_i.jpg',...
        'emergent_colour_j.jpg',...
        'emergent_colour_k.jpg',...
        'emergent_colour_l.jpg',...
        'emergent_colour_m.jpg',...
        'emergent_colour_n.jpg',...
        'emergent_colour_o.jpg',...
        'emergent_colour_p.jpg',...
        'emergent_colour_q.jpg',...
        'emergent_colour_r.jpg',...
        'emergent_colour_s.jpg',...
        'emergent_colour_t.jpg',...
        'emergent_colour_u.jpg',...
        'emergent_colour_w.jpg',...
        'emergent_colour_v.jpg',...
        'emergent_colour_x.jpg',...
        'emergent_colour_y.jpg',...
        'emergent_colour_z.jpg'
    };
    trivial_image_names = {
        'trivial_colour_zero.jpg', ...
        'trivial_colour_one.jpg', ...
        'trivial_colour_two.jpg', ...
        'trivial_colour_three.jpg', ...
        'trivial_colour_four.jpg', ...
        'trivial_colour_five.jpg', ...
        'trivial_colour_six.jpg', ...
        'trivial_colour_seven.jpg', ...
        'trivial_colour_eight.jpg', ...
        'trivial_colour_nine.jpg',...
        'trivial_colour_a.jpg',...
        'trivial_colour_b.jpg',...
        'trivial_colour_c.jpg',...
        'trivial_colour_d.jpg',...
        'trivial_colour_e.jpg',...
        'trivial_colour_f.jpg',...
        'trivial_colour_g.jpg',...
        'trivial_colour_h.jpg',...
        'trivial_colour_i.jpg',...
        'trivial_colour_j.jpg',...
        'trivial_colour_k.jpg',...
        'trivial_colour_l.jpg',...
        'trivial_colour_m.jpg',...
        'trivial_colour_n.jpg',...
        'trivial_colour_o.jpg',...
        'trivial_colour_p.jpg',...
        'trivial_colour_q.jpg',...
        'trivial_colour_r.jpg',...
        'trivial_colour_s.jpg',...
        'trivial_colour_t.jpg',...
        'trivial_colour_u.jpg',...
        'trivial_colour_w.jpg',...
        'trivial_colour_v.jpg',...
        'trivial_colour_x.jpg',...
        'trivial_colour_y.jpg',...
        'trivial_colour_z.jpg'
    };
    color_image_names = {
        'zero_color.jpg', ...
        'one_color.jpg', ...
        'two_color.jpg', ...
        'three_color.jpg', ...
        'four_color.jpg', ...
        'five_color.jpg', ...
        'six_color.jpg', ...
        'seven_color.jpg', ...
        'eight_color.jpg', ...
        'nine_color.jpg'
    };
    gray_image_names = {
        'zero_gray.jpg', ...
        'one_gray.jpg', ...
        'two_gray.jpg', ...
        'three_gray.jpg', ...
        'four_gray.jpg', ...
        'five_gray.jpg', ...
        'six_gray.jpg', ...
        'seven_gray.jpg', ...
        'eight_gray.jpg', ...
        'nine_gray.jpg'
    };

    white_image_names = {
        'zero_white.jpg', ...
        'one_white.jpg', ...
        'two_white.jpg', ...
        'three_white.jpg', ...
        'four_white.jpg', ...
        'five_white.jpg', ...
        'six_white.jpg', ...
        'seven_white.jpg', ...
        'eight_white.jpg', ...
        'nine_white.jpg'
    };
    bin_color_white_image_names = {
        'zero_binare_color_white.jpg', ...
        'one_binare_color_white.jpg', ...
        'two_binare_color_white.jpg', ...
        'three_binare_color_white.jpg', ...
        'four_binare_color_white.jpg', ...
        'five_binare_color_white.jpg', ...
        'six_binare_color_white.jpg', ...
        'seven_binare_color_white.jpg', ...
        'eight_binare_color_white.jpg', ...
        'nine_binare_color_white.jpg'
    };
    bin_color_image_names = {
        'zero_binare_color.jpg', ...
        'one_binare_color.jpg', ...
        'two_binare_color.jpg', ...
        'three_binare_color.jpg', ...
        'four_binare_color.jpg', ...
        'five_binare_color.jpg', ...
        'six_binare_color.jpg', ...
        'seven_binare_color.jpg', ...
        'eight_binare_color.jpg', ...
        'nine_binare_color.jpg'
    };
    images = {};
  
     for name = trivial_image_names;
        image = imread(fullfile(images_dir, name{1}));        
        % image = rgb2gray(image);
        % Normalise image
        image = image./255;
        images{end + 1} = image;
    end
    dimensions = size(image);
    disp(dimensions);
end
 