function [dimensions, images] = load_images()
    images_dir = 'images/';
    image_names = {
        'zero.jpg', ...
        'one.jpg', ...
        'two.jpg', ...
        'three.jpg', ...
        'four.jpg', ...
        'five.jpg', ...
        'six.jpg', ...
        'seven.jpg', ...
        'eight.jpg', ...
        'nine.jpg',...
        'a.jpg',...
        'b.jpg',...
        'c.jpg',...
        'd.jpg',...
        'e.jpg',...
        'f.jpg',...
        'g.jpg',...
        'h.jpg',...
        'i.jpg',...
        'j.jpg',...
        'k.jpg',...
        'l.jpg',...
        'm.jpg',...
        'n.jpg',...
        'o.jpg',...
        'p.jpg',...
        'q.jpg',...
        'r.jpg',...
        's.jpg',...
        't.jpg',...
        'u.jpg',...
        'w.jpg',...
        'v.jpg',...
        'x.jpg',...
        'y.jpg',...
        'z.jpg'
    };
    color_image_names = {
        'zero_color.jpg', ...
        'one_color.jpg', ...
        'two_color.jpg', ...
        'three_color.jpg', ...
        'four_color.jpg', ...
        'five_color.jpg', ...
        'six_color.jpg', ...
        'seven_color.jpg', ...
        'eight_color.jpg', ...
        'nine_color.jpg'
    };
    gray_image_names = {
        'zero_gray.jpg', ...
        'one_gray.jpg', ...
        'two_gray.jpg', ...
        'three_gray.jpg', ...
        'four_gray.jpg', ...
        'five_gray.jpg', ...
        'six_gray.jpg', ...
        'seven_gray.jpg', ...
        'eight_gray.jpg', ...
        'nine_gray.jpg'
    };

    white_image_names = {
        'zero_white.jpg', ...
        'one_white.jpg', ...
        'two_white.jpg', ...
        'three_white.jpg', ...
        'four_white.jpg', ...
        'five_white.jpg', ...
        'six_white.jpg', ...
        'seven_white.jpg', ...
        'eight_white.jpg', ...
        'nine_white.jpg'
    };
    bin_color_white_image_names = {
        'zero_binare_color_white.jpg', ...
        'one_binare_color_white.jpg', ...
        'two_binare_color_white.jpg', ...
        'three_binare_color_white.jpg', ...
        'four_binare_color_white.jpg', ...
        'five_binare_color_white.jpg', ...
        'six_binare_color_white.jpg', ...
        'seven_binare_color_white.jpg', ...
        'eight_binare_color_white.jpg', ...
        'nine_binare_color_white.jpg'
    };
    bin_color_image_names = {
        'zero_binare_color.jpg', ...
        'one_binare_color.jpg', ...
        'two_binare_color.jpg', ...
        'three_binare_color.jpg', ...
        'four_binare_color.jpg', ...
        'five_binare_color.jpg', ...
        'six_binare_color.jpg', ...
        'seven_binare_color.jpg', ...
        'eight_binare_color.jpg', ...
        'nine_binare_color.jpg'
    };
    images = {};
    for name = image_names;
        image = imread(fullfile(images_dir, name{1}));        
        % image = rgb2gray(image);
        % Synaesthetic input
        Isynaesthesia = 0.08;
        % % permeate all of the elements in the current alterbnatively could also
        % 
        % image = image + round(Isynaesthesia * image_m);
        % randomly permeate along a gaussian distribution
       	Prob = reshape(randsample([0, 1], prod(size(image)), true, [0.5-Isynaesthesia, 0.5+Isynaesthesia]), size(image));
        image = double(image) + double((Prob*127).*(image<127));
        images{end + 1} = image;
    end
    dimensions = size(image);
    disp(dimensions);
end
 
