function [model] = simulate_model(model, params)
    otherdims =repmat({':'},1, length(model.dimensions));
    for i = 1 : params.n - 1
        if rem(i, 1000) == 0
            disp([i, params.n]);
        end
        [model.V_line(:,i + 1), ...
         model.U_line(:,1), ...
         model.G(:,1), ...
         model.Isyn_line, ...
         model.Mask_line, ...
         model.Iapp_v_full(otherdims{:},i)] = ...
            step_neurons(model.V_line(:,i), ...
                         model.U_line(:,1), ...
                         model.G(:,1), ...
                         model.T_Iapp_met(i), ...
                         model.Iapp, ...
                         model.Isyn_line, ...
                         model.Post, ...
                         model.Pre, ...
                         model.Iastro_neuron_line(:,1), ...
                         model.I_poisson_noise(:,i), ...
                         model.dimensions);

        [model.neuron_astrozone_activity(otherdims{:}, 1), ...
         model.neuron_astrozone_spikes(otherdims{:}, i)] = ...
            get_neuron_astrozone_activity(model.G(:,1), model.Mask_line, ...
                         model.dimensions);

        [model.Ca(:,:,1), ...
         model.H(:,:,1), ...
         model.IP3(:,:,1), ...
         model.Iastro_neuron, ...
         model.Ineuro] = ...
            step_astrocytes(model.neuron_astrozone_activity(otherdims{:},1), ...
                            model.neuron_astrozone_spikes, ...
                            model.Ineuro, i, ...
                            model.Ca(:,:,1), ...
                            model.H(:,:,1), ...
                            model.IP3(:,:,1), ...
                            model.Iastro_neuron, model.dimensions);

        [model.Iastro_neuron_line(:,1), ...
         model.Ca_size_neuros(otherdims{:}, i)] = ...
            expand_astrocytes(model.Ca(:,:,1), ...
                              model.Iastro_neuron(:,:,i), ...
                              model.dimensions);
    end
end